### ISSUE TITLE
Build fails under Windows 10, "No such property: ossrhUsername for class..."

### ISSUE THREAD

**Issue by gbmhunter** [bitstormGER/jlatexmathfx#2]
Fails with error:

```
A problem occurred evaluating root project 'jlatexmathfx'.
> No such property: ossrhUsername for class: org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer
A problem occurred evaluating root project 'jlatexmathfx'.
> No such property: ossrhUsername for class: org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer
```

Exact error is shown in screenshot below:

![image](https://cloud.githubusercontent.com/assets/2396869/14637042/034311dc-0683-11e6-9b3e-d9b9be01de57.png)

**Comment by bitstormFA** [comment]
I have fixed the build file - if you build the current version with `gradle jar` it should work. 
The error is not related to windows. 
Please let me know if this works for you - my test on windows worked
