### ISSUE TITLE
Bug: sizing behaviour in LateXMathSkin

### ISSUE THREAD

**Issue by spockoyno** [bitstormGER/jlatexmathfx#4]
The current definition
protected double computeMaxWidth(... ) {
        return computePrefHeight(...);
    }
leads to incorrect sizing behaviour. Shouldn't the method be returning 
computePrefWidth(...) ;
instead?

**Comment by spockoyno** [comment]
@bitstormGER I've re-implemented the LateXMathSkin and LateXMathControl classes to address this issue, as well as Issues 5 and 6. I can contribute these, if necessary.
In any case, thanks for a very useful library!

**Comment by bitstormFA** [comment]
Hi,

Excellent help! If you could contribute a Patch this would safe a lot of work.
I will prepare a new patch release asap.

It's great to see the library finally being used! Many thanks @spockoyno

**Comment by bitstormFA** [comment]
will be fixed in 0.3.3
